GET http://localhost:3000/books.json

###
POST http://localhost:3000/books.json
content-type: application/json

{
  "title": "12 Rules for Life",
  "author": "Jordan Peterson",
  "year": 2018
}

###
GET http://localhost:3000/books/101.json

###
PATCH http://localhost:3000/books/102.json
content-type: application/json

{
  "title": "Beyond Order",
  "author": "Jordan Peterson",
  "year": 2021
}

###
DELETE http://localhost:3000/books/102.json